### ISSUE TITLE
Can the application rely on Docker and  Docker Compose?

### ISSUE THREAD

**Issue by NickVeld** [source-ag/assignment-software-engineering#3]
Dear Reader,

https://github.com/source-ag/assignment-software-engineering/blob/6def0ac6cccd9719dd4bf00b81f032ca9a46292c/assignment.md?plain=1#L63-L64

Does the machine have local Docker Engine? Does it work with Docker-compose?

**Comment by DonDebonair** [comment]
Yes, you can assume so

**Comment by NickVeld** [comment]
Thank you!
